# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/pdas/AppData/Local/Temp/ariNewUiweViXd.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import threading
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtCore, QtGui, QtWidgets
import cv2
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QVBoxLayout, QScrollArea, QWidget, QLabel
from PyQt5.QtGui import QImage, QPixmap, QFont
from PyQt5.QtCore import Qt, QTimer
from PyQt5.QtWidgets import QLabel


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1166, 725)
        MainWindow.setStyleSheet("# MainWindow{\n"
"display: flex;\n"
"flex-direction: column;\n"
"align-item : center;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.show_page = QtWidgets.QLabel(self.centralwidget)
        # self.show_page.setGeometry(QtCore.QRect(700, 10, 231, 601))
        self.show_page.setFrameShape(QtWidgets.QFrame.Box)
        self.show_page.setText("")
        self.show_page.setStyleSheet("QLabel {"
                             "border: 2px solid #0e86f6;"  # Change 'red' to desired border color
                             "border-radius: 10px;"   # Adjust the value for desired curve
                             "}")
        # Set fixed width and height
        self.show_page.setFixedSize(231, 980)
        self.show_page.setObjectName("show_page")
        # Create QVBoxLayout for buttons
        self.buttons_layout = QtWidgets.QVBoxLayout()
        # Add QLabel to layout
        self.layout.addWidget(self.show_page, alignment=QtCore.Qt.AlignRight)
        # Set layout to central widget
        # self.centralwidget.setLayout(self.layout)
        # self.btn_label = QtWidgets.QLabel(self.centralwidget)
        # self.btn_label.setGeometry(QtCore.QRect(206, 479, 381, 41))
        # self.btn_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        # self.btn_label.setText("")
        # self.btn_label.setObjectName("btn_label")
        # self.buttons_layout.addWidget(self.btn_label)
        self.pdf_btn = QtWidgets.QPushButton(self.centralwidget)
        self.pdf_btn.setGeometry(QtCore.QRect(710, 20, 211, 31))
        self.pdf_btn.setStyleSheet("QPushButton {\n"
"background-color: #0e86f6;\n"
"        border-radius: 20px; \n"
"    color: white; /* Text color */\n"
"    font-weight: bold;\n"
"border:none; /* Border color */\n"
"    padding: 10px 10px; /* Adjust padding as needed */\n"
"    margin:0px; /* Margin to create distance between buttons */\n"
"}\n"
" QPushButton {\n"
"        border-radius: 10px; /* Adjust the value to change the curve radius */\n"
"    color: white; /* Text color */\n"
"    font-weight: bold;\n"
"\n"
"    padding: 10px 20px;\n"
"        /*height:50px;*/\n"
"margin: 0px;\n"
"        \n"
"        /* border-bottom: 1px solid #b0b0b0; */\n"
"    }\n"
"QPushButton:hover {\n"
"        background-color:#073c6d\n"
"    }")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icons/pdf_icon-icons.com_70898.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pdf_btn.setIcon(icon)
        self.pdf_btn.setIconSize(QtCore.QSize(25, 25))
        self.pdf_btn.setCheckable(True)
        self.pdf_btn.setAutoExclusive(True)
        self.pdf_btn.setFlat(False)
        self.pdf_btn.setObjectName("pdf_btn")
        self.buttons_layout.addWidget(self.pdf_btn, alignment=QtCore.Qt.AlignTop)
        self.edit_btn = QtWidgets.QPushButton(self.centralwidget)
        self.edit_btn.setGeometry(QtCore.QRect(710, 60, 101, 31))
        self.edit_btn.setStyleSheet("QPushButton {\n"
"background-color: #0e86f6;\n"
"        border-radius: 20px; \n"
"    color: white; /* Text color */\n"
"    font-weight: bold;\n"
"border:none; /* Border color */\n"
"    padding: 10px 10px; /* Adjust padding as needed */\n"
"    margin:0px; /* Margin to create distance between buttons */\n"
"}\n"
" QPushButton {\n"
"        border-radius: 10px; /* Adjust the value to change the curve radius */\n"
"    color: white; /* Text color */\n"
"    font-weight: bold;\n"
"\n"
"    padding: 10px 20px;\n"
"        /*height:50px;*/\n"
"margin: 0px;\n"
"        \n"
"        /* border-bottom: 1px solid #b0b0b0; */\n"
"    }\n"
" QPushButton:hover {\n"
"        background-color:#073c6d\n"
"    }")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/edit.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.edit_btn.setIcon(icon1)
        self.edit_btn.setObjectName("edit_btn")
        self.buttons_layout.addWidget(self.edit_btn, alignment=QtCore.Qt.AlignTop)
        self.delete_btn = QtWidgets.QPushButton(self.centralwidget)
        self.delete_btn.setGeometry(QtCore.QRect(820, 60, 101, 31))
        self.delete_btn.setStyleSheet("QPushButton {\n"
"background-color: #0e86f6;\n"
"        border-radius: 20px; \n"
"    color: white; /* Text color */\n"
"    font-weight: bold;\n"
"border:none; /* Border color */\n"
"    padding: 10px 10px; /* Adjust padding as needed */\n"
"    margin:0px; /* Margin to create distance between buttons */\n"
"}\n"
" QPushButton {\n"
"        border-radius: 10px; /* Adjust the value to change the curve radius */\n"
"    color: white; /* Text color */\n"
"    font-weight: bold;\n"
"\n"
"    padding: 10px 20px;\n"
"        /*height:50px;*/\n"
"margin: 0px;\n"
"        \n"
"        /* border-bottom: 1px solid #b0b0b0; */\n"
"    }\n"
" QPushButton:hover {\n"
"        background-color:#073c6d\n"
"    }")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/icons/Delete.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_btn.setIcon(icon2)
        self.delete_btn.setObjectName("delete_btn")
        self.buttons_layout.addWidget(self.delete_btn, alignment=QtCore.Qt.AlignTop)
        self.hor_line = QtWidgets.QFrame(self.centralwidget)
        self.hor_line.setGeometry(QtCore.QRect(730, 100, 171, 16))
        self.hor_line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.hor_line.setStyleSheet("QFrame {"
                             "border: 2px solid #0e86f6;"  # Change '#0e86f6' to desired border color
                             "border-radius: 10px;"   # Adjust the value for desired curve
                             "}")
        self.hor_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.hor_line.setObjectName("hor_line")
        self.buttons_layout.addWidget(self.hor_line, alignment=QtCore.Qt.AlignTop)
         # Add some stretch to move the buttons to the bottom
        self.buttons_layout.addStretch()
        
        # Set layout for show_page
        self.show_page.setLayout(self.buttons_layout)
         # Set layout to central widget
        self.centralwidget.setLayout(self.layout)

        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1800, 1051))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.cam_label = QtWidgets.QLabel(self.page)
        self.cam_label.setGeometry(QtCore.QRect(300, 80, 991, 731))
        self.cam_label.setFrameShape(QtWidgets.QFrame.Box)
        self.cam_label.setText("")
        self.cam_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cam_label.setObjectName("cam_label")
        self.cam_label.setStyleSheet("QLabel {"
                             "border: 2px solid #0e86f6;"  # Change 'red' to desired border color
                             "border-radius: 10px;"   # Adjust the value for desired curve
                             "}")
        self.cam_drop_down = QtWidgets.QComboBox(self.page)
        self.cam_drop_down.setGeometry(QtCore.QRect(700, 20, 181, 22))
        self.cam_drop_down.setObjectName("cam_drop_down")
        self.shutter_btn = QtWidgets.QPushButton(self.page)
        self.shutter_btn.setGeometry(QtCore.QRect(750, 880, 81, 41))
        self.shutter_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/icons/camera48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shutter_btn.setIcon(icon3)
        self.shutter_btn.setIconSize(QtCore.QSize(40, 40))
        self.shutter_btn.setCheckable(True)
        self.shutter_btn.setAutoExclusive(True)
        self.shutter_btn.setFlat(True)
        self.shutter_btn.setObjectName("shutter_btn")
        # self.res_drop_down = QtWidgets.QComboBox(self.page)
        # self.res_drop_down.setGeometry(QtCore.QRect(400, 550, 181, 22))
        # self.res_drop_down.setObjectName("res_drop_down")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.menu = QtWidgets.QWidget(self.page_2)
        self.menu.setGeometry(QtCore.QRect(0, 0, 200, 1041))
        self.menu.setStyleSheet("#menu {\n"
"        background-color:#0e86f6 ;\n"
"        width:50px;\n"
"    }\n"
"\n"
"    /* style for QPushButton and QLabel */\n"
"    #menu QPushButton {\n"
"        border-radius: 10px; /* Adjust the value to change the curve radius */\n"
"    color: white; /* Text color */\n"
"    font-weight: bold;\n"
" border: 2px solid #4CAF50; /* Border color */\n"
"    padding: 10px 20px;\n"
"        /*height:50px;*/\n"
"margin: 10px;\n"
"        \n"
"        /* border-bottom: 1px solid #b0b0b0; */\n"
"    }\n"
"#menu Qlabel{\n"
"border-radius: 10px; /* Adjust the value to change the curve radius */\n"
"    color: white; /* Text color */\n"
"    font-weight: bold;\n"
" border: 2px solid #4CAF50; /* Border color */\n"
"    padding: 10px 20px;\n"
"        /*height:50px;*/\n"
"margin: 10px;\n"
"}\n"
"\n"
"    #menu QPushButton:hover {\n"
"        background-color:#073c6d\n"
"    }\n"
"")
        self.menu.setObjectName("menu")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.menu)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.dash_label = QtWidgets.QLabel(self.menu)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.dash_label.setFont(font)
        self.dash_label.setStyleSheet(" #menu QLabel{\n"
"padding-top: 10px;\n"
"    color: white; /* Text color */\n"
"    font-weight: bold;\n"
" \n"
"}")
        self.dash_label.setAlignment(QtCore.Qt.AlignCenter)
        self.dash_label.setObjectName("dash_label")
        self.verticalLayout_16.addWidget(self.dash_label)
        self.adjust_btn = QtWidgets.QPushButton(self.menu)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.adjust_btn.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/icons/adjust.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/icons/adjust.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.adjust_btn.setIcon(icon3)
        self.adjust_btn.setCheckable(True)
        self.adjust_btn.setAutoExclusive(True)
        self.adjust_btn.setFlat(False)
        self.adjust_btn.setObjectName("adjust_btn")
        self.verticalLayout_16.addWidget(self.adjust_btn)
        self.color_btn = QtWidgets.QPushButton(self.menu)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/icons/ColorMode.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/icons/ColorMode.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.color_btn.setIcon(icon4)
        self.color_btn.setCheckable(True)
        self.color_btn.setAutoExclusive(True)
        self.color_btn.setObjectName("color_btn")
        self.verticalLayout_16.addWidget(self.color_btn)
        self.rotate_btn = QtWidgets.QPushButton(self.menu)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/icons/rotate_113592.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rotate_btn.setIcon(icon5)
        self.rotate_btn.setObjectName("rotate_btn")
        self.verticalLayout_16.addWidget(self.rotate_btn)
        self.crop_btn = QtWidgets.QPushButton(self.menu)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/icons/crop.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/icons/crop.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.crop_btn.setIcon(icon6)
        self.crop_btn.setCheckable(True)
        self.crop_btn.setAutoExclusive(True)
        self.crop_btn.setObjectName("crop_btn")
        self.verticalLayout_16.addWidget(self.crop_btn)
        self.cam_back = QtWidgets.QPushButton(self.menu)
        self.cam_back.setStyleSheet("QPushButton {\n"
"\n"
"        border-radius: 20px; \n"
"    color: white; /* Text color */\n"
"    font-weight: bold;\n"
"border:none; /* Border color */\n"
"    padding: 10px 10px; /* Adjust padding as needed */\n"
"    margin: 10px; /* Margin to create distance between buttons */\n"
"}")
        self.cam_back.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/newPrefix/camera_back.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cam_back.setIcon(icon7)
        self.cam_back.setIconSize(QtCore.QSize(35, 35))
        self.cam_back.setCheckable(True)
        self.cam_back.setAutoExclusive(True)
        self.cam_back.setObjectName("cam_back")
        self.verticalLayout_16.addWidget(self.cam_back)
        self.verticalLayout_15.addLayout(self.verticalLayout_16)
        spacerItem = QtWidgets.QSpacerItem(20, 322, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem)
        self.show_image = QtWidgets.QLabel(self.page_2)
        self.show_image.setGeometry(QtCore.QRect(680, 30, 571, 461))
        self.show_image.setFrameShape(QtWidgets.QFrame.Box)
        self.show_image.setText("")
        self.show_image.setStyleSheet("QLabel {"
                             "border: 2px solid #0e86f6;"  # Change 'red' to desired border color
                             "border-radius: 10px;"   # Adjust the value for desired curve
                             "}")
        self.show_image.setObjectName("show_image")
        self.edit_stack = QtWidgets.QStackedWidget(self.page_2)
        self.edit_stack.setGeometry(QtCore.QRect(780, 520, 371, 81))
        self.edit_stack.setObjectName("edit_stack")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.horizontalSlider = QtWidgets.QSlider(self.page_3)
        self.horizontalSlider.setGeometry(QtCore.QRect(10, 50, 160, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.page_3)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(210, 50, 160, 22))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.label = QtWidgets.QLabel(self.page_3)
        self.label.setGeometry(QtCore.QRect(60, 10, 81, 41))
        self.label.setStyleSheet("QLabel {\n"
"    font-size: 16px; /* Change the font size to 16 pixels */\n"
"    color: #0e86f6; /* Change the font color to red */\n"
"}")
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.page_3)
        self.label_2.setGeometry(QtCore.QRect(250, 10, 71, 41))
        self.label_2.setStyleSheet("QLabel {\n"
"    font-size: 16px; /* Change the font size to 16 pixels */\n"
"    color: #0e86f6; /* Change the font color to red */\n"
"}")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.edit_stack.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.edit_stack.addWidget(self.page_4)
        self.undo_btn = QtWidgets.QPushButton(self.page_2)
        self.undo_btn.setGeometry(QtCore.QRect(650, 650, 91, 31))
        self.undo_btn.setStyleSheet("QPushButton {\n"
"background-color: #0e86f6;\n"
"        border-radius: 20px; \n"
"    color: white; /* Text color */\n"
"    font-weight: bold;\n"
"border:none; /* Border color */\n"
"    padding: 10px 10px; /* Adjust padding as needed */\n"
"    margin:0px; /* Margin to create distance between buttons */\n"
"}\n"
" QPushButton {\n"
"        border-radius: 10px; /* Adjust the value to change the curve radius */\n"
"    color: white; /* Text color */\n"
"    font-weight: bold;\n"
"\n"
"    padding: 10px 20px;\n"
"        /*height:50px;*/\n"
"margin: 0px;\n"
"        \n"
"        /* border-bottom: 1px solid #b0b0b0; */\n"
"    }\n"
" QPushButton:hover {\n"
"        background-color:#073c6d\n"
"    }")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/newPrefix/icons/undo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.undo_btn.setIcon(icon8)
        self.undo_btn.setObjectName("undo_btn")
        self.discard_btn = QtWidgets.QPushButton(self.page_2)
        self.discard_btn.setGeometry(QtCore.QRect(940, 650, 101, 31))
        self.discard_btn.setStyleSheet("QPushButton {\n"
"background-color: #0e86f6;\n"
"        border-radius: 20px; \n"
"    color: white; /* Text color */\n"
"    font-weight: bold;\n"
"border:none; /* Border color */\n"
"    padding: 10px 10px; /* Adjust padding as needed */\n"
"    margin:0px; /* Margin to create distance between buttons */\n"
"}\n"
" QPushButton {\n"
"        border-radius: 10px; /* Adjust the value to change the curve radius */\n"
"    color: white; /* Text color */\n"
"    font-weight: bold;\n"
"\n"
"    padding: 10px 20px;\n"
"        /*height:50px;*/\n"
"margin: 0px;\n"
"        \n"
"        /* border-bottom: 1px solid #b0b0b0; */\n"
"    }\n"
" QPushButton:hover {\n"
"        background-color:#073c6d\n"
"    }")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/newPrefix/cancelled.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.discard_btn.setIcon(icon9)
        self.discard_btn.setObjectName("discard_btn")
        self.save_btn = QtWidgets.QPushButton(self.page_2)
        self.save_btn.setGeometry(QtCore.QRect(1200, 650, 91, 31))
        self.save_btn.setStyleSheet("QPushButton {\n"
"background-color: #0e86f6;\n"
"        border-radius: 20px; \n"
"    color: white; /* Text color */\n"
"    font-weight: bold;\n"
"border:none; /* Border color */\n"
"    padding: 10px 10px; /* Adjust padding as needed */\n"
"    margin:0px; /* Margin to create distance between buttons */\n"
"}\n"
" QPushButton {\n"
"        border-radius: 10px; /* Adjust the value to change the curve radius */\n"
"    color: white; /* Text color */\n"
"    font-weight: bold;\n"
"\n"
"    padding: 10px 20px;\n"
"        /*height:50px;*/\n"
"margin: 0px;\n"
"        \n"
"        /* border-bottom: 1px solid #b0b0b0; */\n"
"    }\n"
"\n"
" QPushButton:hover {\n"
"        background-color:#073c6d\n"
"    }")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/newPrefix/icons/save.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_btn.setIcon(icon10)
        self.save_btn.setObjectName("save_btn")
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.edit_stack.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pdf_btn.setText(_translate("MainWindow", " Convert to PDF"))
        self.edit_btn.setText(_translate("MainWindow", "edit"))
        self.delete_btn.setText(_translate("MainWindow", "delete"))
        self.dash_label.setText(_translate("MainWindow", "Edit"))
        self.adjust_btn.setText(_translate("MainWindow", "Adjust"))
        self.color_btn.setText(_translate("MainWindow", "Color Mode"))
        self.rotate_btn.setText(_translate("MainWindow", "Rotate"))
        self.crop_btn.setText(_translate("MainWindow", "Crop"))
        self.label.setText(_translate("MainWindow", "Contrast"))
        self.label_2.setText(_translate("MainWindow", "Sharpness"))
        self.undo_btn.setText(_translate("MainWindow", "Undo"))
        self.discard_btn.setText(_translate("MainWindow", "Discard"))
        self.save_btn.setText(_translate("MainWindow", "Save"))
import Stackresource_rc
import camResource_rc


class VideoStream:
    def __init__(self, parent_label: QLabel, camera_index):
        self.video = cv2.VideoCapture(cv2.CAP_ANY)

        self.parent_label = parent_label
        self.set_resolution()
        self.timer = None
        self.camera_change_thread = None  # Thread for camera switching

    def set_resolution(self):
        # Check if camera is open
        if not self.video.isOpened():
            print("Error opening camera")
            return

        # Check if 4K resolution is supported
        # Typo fix in height value
        self.video.set(cv2.CAP_PROP_FRAME_WIDTH, 3840)
        self.video.set(cv2.CAP_PROP_FRAME_HEIGHT, 2160)
        width = int(self.video.get(cv2.CAP_PROP_FRAME_WIDTH))
        height = int(self.video.get(cv2.CAP_PROP_FRAME_HEIGHT))

        print(width)
        print(height)
        # if width == 3840 and height == 2160:
        #     print("Using 4K resolution")
        # else:
        #     self.video.set(cv2.CAP_PROP_FRAME_WIDTH, 1920)
        #     self.video.set(cv2.CAP_PROP_FRAME_HEIGHT, 1080)
        #     print("Using 1080p resolution")
        # ... (rest of your set_resolution logic)

    def display_camera_feed(self):
        if not self.video.isOpened():
            # Display error message if camera not open
          font = QFont()
          font.setPointSize(30)
          self.parent_label.setFont(font)
          self.parent_label.setText("<p style='font-size:20pt'>Changing Camera...</p>")
          return

        ret, frame = self.video.read()
        if ret:
            rgb_image = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            frame_resized = cv2.resize(rgb_image, (640, 480))
            h, w, ch = frame_resized.shape
            bytes_per_line = ch * w
            q_img = QImage(frame_resized.data, w, h, bytes_per_line, QImage.Format_RGB888)
            pixmap = QPixmap.fromImage(q_img)
            self.parent_label.setPixmap(pixmap.scaled(self.parent_label.size(), Qt.KeepAspectRatio))
            
            # self.parent_label.setFixedSize(w, h)
        else:
            # Display loader while camera is changing
            self.show_loader()

    def change_camera(self, camera_index):
        # Stop the timer if it's running
        if self.timer is not None:
            self.timer.stop()

        # Create a thread for camera switching (optional, but recommended for responsiveness)
        self.camera_change_thread = threading.Thread(target=self._change_camera_in_thread, args=(camera_index,))
        self.camera_change_thread.start()
        # Display loader immediately
        self.show_loader()

    def _change_camera_in_thread(self, camera_index):
        # Release the current video capture
        self.video.release()

        # Open the new camera capture
        self.video = cv2.VideoCapture(camera_index, cv2.CAP_DSHOW)
        self.set_resolution()

        # Create a QTimer object and connect it to the display_camera_feed function (in main thread)
        self.timer = QTimer()
        self.timer.timeout.connect(self.display_camera_feed)
        self.timer.start(10)  # Start the timer with a 10ms interval

    def show_loader(self):
        font = QFont()
        font.setPointSize(30)
        self.parent_label.setFont(font)
        self.parent_label.setAlignment(Qt.AlignCenter) 
        self.parent_label.setText("<p style='font-size:20pt'>Changing Camera...</p>")
