# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/pdas/AppData/Local/Temp/camDesignBrmUqu.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(798, 579)
        MainWindow.setStyleSheet("background-color:white;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # Create layouts
        self.mainLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.camLayout = QtWidgets.QVBoxLayout()
        self.showLayout = QtWidgets.QVBoxLayout()
        # Add layouts to central widget
        self.mainLayout.addLayout(self.camLayout)
        self.mainLayout.addLayout(self.showLayout)




        self.cam_label = QtWidgets.QLabel(self.centralwidget)
        # self.cam_label.setGeometry(QtCore.QRect(60, 50, 491, 431))
        self.cam_label.setFrameShape(QtWidgets.QFrame.Box)
        self.cam_label.setText("")
        self.cam_label.setObjectName("cam_label")
        self.cam_label.setFixedHeight(500)
        self.camLayout.addWidget(self.cam_label)
        self.show_label = QtWidgets.QLabel(self.centralwidget)
        # self.show_label.setGeometry(QtCore.QRect(610, 10, 151, 471))
        self.show_label.setFrameShape(QtWidgets.QFrame.Box)
        self.show_label.setText("")
        self.show_label.setObjectName("show_label")
        self.show_label.setFixedWidth(200)
        self.showLayout.addWidget(self.show_label)
        self.shutter_btn = QtWidgets.QPushButton(self.centralwidget)
        # self.shutter_btn.setGeometry(QtCore.QRect(250, 510, 81, 41))
        self.shutter_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icons/camera48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shutter_btn.setIcon(icon)
        self.shutter_btn.setIconSize(QtCore.QSize(40, 40))
        self.shutter_btn.setCheckable(True)
        self.shutter_btn.setAutoExclusive(True)
        self.shutter_btn.setFlat(True)
        self.shutter_btn.setObjectName("shutter_btn")
        self.camLayout.addWidget(self.shutter_btn, alignment=QtCore.Qt.AlignCenter)
        self.done_btn = QtWidgets.QPushButton(self.centralwidget)
        # self.done_btn.setGeometry(QtCore.QRect(650, 510, 75, 23))
        self.done_btn.setStyleSheet("#done_btn QPushButton:hover {\n"
"        background-color: rgba( 86, 101, 115, 0.5);\n"
"    }")
        self.done_btn.setStyleSheet("background-color: #039FDB; color: white;")
        self.done_btn.setCheckable(True)
        self.done_btn.setAutoRepeat(False)
        self.done_btn.setAutoExclusive(True)
        self.done_btn.setObjectName("done_btn")
        self.camLayout.addWidget(self.done_btn, alignment=QtCore.Qt.AlignCenter)
        self.drop_down = QtWidgets.QComboBox(self.centralwidget)
        # self.drop_down.setGeometry(QtCore.QRect(230, 10, 69, 22))
        self.drop_down.setObjectName("drop_down")
        self.camLayout.addWidget(self.drop_down, alignment=QtCore.Qt.AlignCenter)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Scanner"))
        self.done_btn.setText(_translate("MainWindow", "Done"))
import camResource_rc
