# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/pdas/AppData/Local/Temp/NewUiHlszuw.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(807, 637)
        MainWindow.setStyleSheet("Mainwindow{\n"
"background-color: white;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 10, 551, 561))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.cam_label = QtWidgets.QLabel(self.page)
        self.cam_label.setGeometry(QtCore.QRect(10, 0, 521, 391))
        self.cam_label.setFrameShape(QtWidgets.QFrame.Box)
        self.cam_label.setText("")
        self.cam_label.setObjectName("cam_label")
        self.shutter_btn = QtWidgets.QPushButton(self.page)
        self.shutter_btn.setGeometry(QtCore.QRect(190, 400, 91, 61))
        self.shutter_btn.setStyleSheet("QPushButton:hover {\n"
"        background-color:#073c6d\n"
"    }\n"
"QPushButton {\n"
"background-color: #0e86f6;\n"
"        border-radius: 20px; \n"
"    color: white; /* Text color */\n"
"    font-weight: bold;\n"
"border:none; /* Border color */\n"
"    padding: 10px 10px; /* Adjust padding as needed */\n"
"    margin:0px; /* Margin to create distance between buttons */\n"
"}\n"
" QPushButton {\n"
"        border-radius: 10px; /* Adjust the value to change the curve radius */\n"
"    color: white; /* Text color */\n"
"    font-weight: bold;\n"
"\n"
"    padding: 10px 20px;\n"
"        /*height:50px;*/\n"
"margin: 0px;\n"
"        \n"
"        /* border-bottom: 1px solid #b0b0b0; */\n"
"    }")
        self.shutter_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icons/camera48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shutter_btn.setIcon(icon)
        self.shutter_btn.setIconSize(QtCore.QSize(40, 40))
        self.shutter_btn.setCheckable(True)
        self.shutter_btn.setAutoExclusive(True)
        self.shutter_btn.setFlat(False)
        self.shutter_btn.setObjectName("shutter_btn")
        self.drop_down = QtWidgets.QComboBox(self.page)
        self.drop_down.setGeometry(QtCore.QRect(400, 420, 69, 22))
        self.drop_down.setStyleSheet("QComboBox {\n"
"        border: 2px solid #0e86f6; /* Border color */\n"
"        border-radius: 5px; /* Rounded corners */\n"
"        padding: 5px; /* Padding inside the box */\n"
"        background-color: white; /* Background color */\n"
"    }\n"
"\n"
"    QComboBox::drop-down {\n"
"        border: none; /* Remove default drop-down arrow */\n"
"        background-color: #0e86f6; /* Background color of the arrow area */\n"
"        subcontrol-origin: padding; /* Positioning of the drop-down arrow */\n"
"        subcontrol-position: right center; /* Positioning of the drop-down arrow */\n"
"        width: 20px; /* Width of the drop-down arrow area */\n"
"        border-top-right-radius: 5px; /* Rounded corners of the arrow area */\n"
"        border-bottom-right-radius: 5px; /* Rounded corners of the arrow area */\n"
"    }\n"
"\n"
"    \n"
"    ")
        self.drop_down.setObjectName("drop_down")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.page_2)
        self.stackedWidget_2.setGeometry(QtCore.QRect(10, 0, 151, 551))
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.menu = QtWidgets.QWidget(self.page_5)
        self.menu.setGeometry(QtCore.QRect(0, 9, 151, 711))
        self.menu.setStyleSheet("#menu {\n"
"        background-color:#0e86f6 ;\n"
"        width:50px;\n"
"    }\n"
"\n"
"    /* style for QPushButton and QLabel */\n"
"    #menu QPushButton {\n"
"        border-radius: 10px; /* Adjust the value to change the curve radius */\n"
"    color: white; /* Text color */\n"
"    font-weight: bold;\n"
" border: 2px solid #4CAF50; /* Border color */\n"
"    padding: 10px 20px;\n"
"        /*height:50px;*/\n"
"margin: 10px;\n"
"        \n"
"        /* border-bottom: 1px solid #b0b0b0; */\n"
"    }\n"
"#menu Qlabel{\n"
"border-radius: 10px; /* Adjust the value to change the curve radius */\n"
"    color: white; /* Text color */\n"
"    font-weight: bold;\n"
" border: 2px solid #4CAF50; /* Border color */\n"
"    padding: 10px 20px;\n"
"        /*height:50px;*/\n"
"margin: 10px;\n"
"}\n"
"\n"
"    #menu QPushButton:hover {\n"
"        background-color:#073c6d\n"
"    }\n"
"")
        self.menu.setObjectName("menu")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.menu)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.adjust_btn = QtWidgets.QPushButton(self.menu)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.adjust_btn.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/icons/adjust.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/icons/adjust.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.adjust_btn.setIcon(icon1)
        self.adjust_btn.setCheckable(True)
        self.adjust_btn.setAutoExclusive(True)
        self.adjust_btn.setFlat(False)
        self.adjust_btn.setObjectName("adjust_btn")
        self.verticalLayout_16.addWidget(self.adjust_btn)
        self.color_btn = QtWidgets.QPushButton(self.menu)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/icons/ColorMode.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/icons/ColorMode.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.color_btn.setIcon(icon2)
        self.color_btn.setCheckable(True)
        self.color_btn.setAutoExclusive(True)
        self.color_btn.setObjectName("color_btn")
        self.verticalLayout_16.addWidget(self.color_btn)
        self.rotate_btn = QtWidgets.QPushButton(self.menu)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/icons/rotate_113592.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rotate_btn.setIcon(icon3)
        self.rotate_btn.setObjectName("rotate_btn")
        self.verticalLayout_16.addWidget(self.rotate_btn)
        self.crop_btn = QtWidgets.QPushButton(self.menu)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/icons/crop.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/icons/crop.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.crop_btn.setIcon(icon4)
        self.crop_btn.setCheckable(True)
        self.crop_btn.setAutoExclusive(True)
        self.crop_btn.setObjectName("crop_btn")
        self.verticalLayout_16.addWidget(self.crop_btn)
        self.cam_back = QtWidgets.QPushButton(self.menu)
        self.cam_back.setStyleSheet("QPushButton {\n"
"\n"
"        border-radius: 20px; \n"
"    color: white; /* Text color */\n"
"    font-weight: bold;\n"
"border:none; /* Border color */\n"
"    padding: 10px 10px; /* Adjust padding as needed */\n"
"    margin: 10px; /* Margin to create distance between buttons */\n"
"}")
        self.cam_back.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/camera_back.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cam_back.setIcon(icon5)
        self.cam_back.setIconSize(QtCore.QSize(35, 35))
        self.cam_back.setCheckable(True)
        self.cam_back.setAutoExclusive(True)
        self.cam_back.setObjectName("cam_back")
        self.verticalLayout_16.addWidget(self.cam_back)
        self.verticalLayout_15.addLayout(self.verticalLayout_16)
        spacerItem = QtWidgets.QSpacerItem(20, 322, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem)
        self.stackedWidget_2.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.adjust_menu = QtWidgets.QWidget(self.page_6)
        self.adjust_menu.setGeometry(QtCore.QRect(0, 0, 151, 616))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(14, 134, 246))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(14, 134, 246))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(14, 134, 246))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(14, 134, 246))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(14, 134, 246))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(14, 134, 246))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(14, 134, 246))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(14, 134, 246))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(14, 134, 246))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.adjust_menu.setPalette(palette)
        self.adjust_menu.setStyleSheet("#adjust_menu {\n"
"        background-color:#0e86f6 ;\n"
"        width:50px;\n"
"    }\n"
"\n"
"    /* style for QPushButton and QLabel */\n"
"    #adjust_menu QPushButton {\n"
"        border-radius: 10px; /* Adjust the value to change the curve radius */\n"
"    color: white; /* Text color */\n"
"    font-weight: bold;\n"
" border: 2px solid #4CAF50; /* Border color */\n"
"    padding: 10px 20px;\n"
"        /*height:50px;*/\n"
"margin: 5px;\n"
"        \n"
"        /* border-bottom: 1px solid #b0b0b0; */\n"
"    }\n"
"#adjust_menu Qlabel{\n"
"border-radius: 10px; /* Adjust the value to change the curve radius */\n"
"    color: white; /* Text color */\n"
"    font-weight: bold;\n"
" border: 2px solid #4CAF50; /* Border color */\n"
"    padding: 10px 20px;\n"
"        /*height:50px;*/\n"
"margin: 10px;\n"
"}\n"
"\n"
"    #adjust_menu QPushButton:hover {\n"
"        background-color:#073c6d\n"
"    }\n"
"\n"
"")
        self.adjust_menu.setObjectName("adjust_menu")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.adjust_menu)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_12 = QtWidgets.QLabel(self.adjust_menu)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_21.addWidget(self.label_12)
        self.back_btn_3 = QtWidgets.QPushButton(self.adjust_menu)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.back_btn_3.setFont(font)
        self.back_btn_3.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/icons/Back.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/icons/Back.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.back_btn_3.setIcon(icon6)
        self.back_btn_3.setCheckable(True)
        self.back_btn_3.setAutoExclusive(True)
        self.back_btn_3.setObjectName("back_btn_3")
        self.verticalLayout_21.addWidget(self.back_btn_3)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.contrast_btn_3 = QtWidgets.QPushButton(self.adjust_menu)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/newPrefix/icons/Contrast.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap(":/newPrefix/icons/Contrast.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.contrast_btn_3.setIcon(icon7)
        self.contrast_btn_3.setCheckable(True)
        self.contrast_btn_3.setAutoExclusive(True)
        self.contrast_btn_3.setObjectName("contrast_btn_3")
        self.verticalLayout_22.addWidget(self.contrast_btn_3)
        self.horizontalSlider_5 = QtWidgets.QSlider(self.adjust_menu)
        self.horizontalSlider_5.setStyleSheet("QSlider::groove:horizontal {\n"
"                background: white; /* Slider background color */\n"
"                height: 2px; /* Slider height */\n"
"                border-radius: 4px; /* Slider border radius */\n"
"            }\n"
"\n"
"            QSlider::handle:horizontal {\n"
"                background:white; /* Slider handle color */\n"
"                border: 2px solid white; /* Slider handle border color */\n"
"                width: 20px; /* Slider handle width */\n"
"                margin: -5px 0; /* Slider handle margin */\n"
"                border-radius: 10px; /* Slider handle border radius */\n"
"            }")
        self.horizontalSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_5.setObjectName("horizontalSlider_5")
        self.verticalLayout_22.addWidget(self.horizontalSlider_5)
        self.sharp_btn_3 = QtWidgets.QPushButton(self.adjust_menu)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/newPrefix/icons/sharpness.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap(":/newPrefix/icons/sharpness.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.sharp_btn_3.setIcon(icon8)
        self.sharp_btn_3.setObjectName("sharp_btn_3")
        self.verticalLayout_22.addWidget(self.sharp_btn_3)
        self.verticalLayout_21.addLayout(self.verticalLayout_22)
        self.horizontalSlider_6 = QtWidgets.QSlider(self.adjust_menu)
        self.horizontalSlider_6.setStyleSheet("QSlider::groove:horizontal {\n"
"                background: white; /* Slider background color */\n"
"                height: 2px; /* Slider height */\n"
"                border-radius: 4px; /* Slider border radius */\n"
"            }\n"
"\n"
"            QSlider::handle:horizontal {\n"
"                background:white; /* Slider handle color */\n"
"                border: 2px solid white; /* Slider handle border color */\n"
"                width: 20px; /* Slider handle width */\n"
"                margin: -5px 0; /* Slider handle margin */\n"
"                border-radius: 10px; /* Slider handle border radius */\n"
"            }")
        self.horizontalSlider_6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_6.setObjectName("horizontalSlider_6")
        self.verticalLayout_21.addWidget(self.horizontalSlider_6)
        spacerItem1 = QtWidgets.QSpacerItem(20, 406, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_21.addItem(spacerItem1)
        self.stackedWidget_2.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.color_menu = QtWidgets.QWidget(self.page_7)
        self.color_menu.setGeometry(QtCore.QRect(0, 0, 151, 541))
        self.color_menu.setStyleSheet("#color_menu {\n"
"        background-color:#0e86f6 ;\n"
"        width:50px;\n"
"    }\n"
"\n"
"    /* style for QPushButton and QLabel */\n"
"    #color_menu QPushButton {\n"
"        border-radius: 10px; /* Adjust the value to change the curve radius */\n"
"    color: white; /* Text color */\n"
"    font-weight: bold;\n"
" border: 2px solid #4CAF50; /* Border color */\n"
"    padding: 10px 20px;\n"
"        /*height:50px;*/\n"
"margin: 5px;\n"
"        \n"
"        /* border-bottom: 1px solid #b0b0b0; */\n"
"    }\n"
"#color_menu Qlabel{\n"
"border-radius: 10px; /* Adjust the value to change the curve radius */\n"
"    color: white; /* Text color */\n"
"    font-weight: bold;\n"
" border: 2px solid #4CAF50; /* Border color */\n"
"    padding: 10px 20px;\n"
"        /*height:50px;*/\n"
"margin: 10px;\n"
"}\n"
"\n"
"    #color_menu QPushButton:hover {\n"
"        background-color:#073c6d\n"
"    }\n"
"")
        self.color_menu.setObjectName("color_menu")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.color_menu)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_13 = QtWidgets.QLabel(self.color_menu)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_23.addWidget(self.label_13)
        self.back_btn_4 = QtWidgets.QPushButton(self.color_menu)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.back_btn_4.setFont(font)
        self.back_btn_4.setText("")
        self.back_btn_4.setIcon(icon6)
        self.back_btn_4.setCheckable(True)
        self.back_btn_4.setAutoExclusive(True)
        self.back_btn_4.setObjectName("back_btn_4")
        self.verticalLayout_23.addWidget(self.back_btn_4)
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.enhance_btn = QtWidgets.QPushButton(self.color_menu)
        self.enhance_btn.setObjectName("enhance_btn")
        self.verticalLayout_24.addWidget(self.enhance_btn)
        self.colorfil_btn = QtWidgets.QPushButton(self.color_menu)
        self.colorfil_btn.setObjectName("colorfil_btn")
        self.verticalLayout_24.addWidget(self.colorfil_btn)
        self.bnw_btn = QtWidgets.QPushButton(self.color_menu)
        self.bnw_btn.setObjectName("bnw_btn")
        self.verticalLayout_24.addWidget(self.bnw_btn)
        self.gray_btn = QtWidgets.QPushButton(self.color_menu)
        self.gray_btn.setObjectName("gray_btn")
        self.verticalLayout_24.addWidget(self.gray_btn)
        self.nofil_btn = QtWidgets.QPushButton(self.color_menu)
        self.nofil_btn.setObjectName("nofil_btn")
        self.verticalLayout_24.addWidget(self.nofil_btn)
        self.verticalLayout_23.addLayout(self.verticalLayout_24)
        spacerItem2 = QtWidgets.QSpacerItem(20, 321, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_23.addItem(spacerItem2)
        self.stackedWidget_2.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.rotate_menu = QtWidgets.QWidget(self.page_8)
        self.rotate_menu.setGeometry(QtCore.QRect(-10, 0, 161, 541))
        self.rotate_menu.setStyleSheet("#rotate_menu {\n"
"        background-color:#0e86f6 ;\n"
"        width:50px;\n"
"    }\n"
"\n"
"    /* style for QPushButton and QLabel */\n"
"    #rotate_menu QPushButton {\n"
"        border-radius: 10px; /* Adjust the value to change the curve radius */\n"
"    color: white; /* Text color */\n"
"    font-weight: bold;\n"
" border: 2px solid #4CAF50; /* Border color */\n"
"    padding: 10px 20px;\n"
"        /*height:50px;*/\n"
"margin: 5px;\n"
"        \n"
"        /* border-bottom: 1px solid #b0b0b0; */\n"
"    }\n"
"#rotate_menu Qlabel{\n"
"border-radius: 10px; /* Adjust the value to change the curve radius */\n"
"    color: white; /* Text color */\n"
"    font-weight: bold;\n"
" border: 2px solid #4CAF50; /* Border color */\n"
"    padding: 10px 20px;\n"
"        /*height:50px;*/\n"
"margin: 10px;\n"
"}\n"
"\n"
"    #rotate_menu QPushButton:hover {\n"
"        background-color:#073c6d\n"
"    }\n"
"\n"
"")
        self.rotate_menu.setObjectName("rotate_menu")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.rotate_menu)
        self.verticalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.label_14 = QtWidgets.QLabel(self.rotate_menu)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_25.addWidget(self.label_14)
        self.back_btn_5 = QtWidgets.QPushButton(self.rotate_menu)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.back_btn_5.setFont(font)
        self.back_btn_5.setText("")
        self.back_btn_5.setIcon(icon6)
        self.back_btn_5.setCheckable(True)
        self.back_btn_5.setAutoExclusive(True)
        self.back_btn_5.setObjectName("back_btn_5")
        self.verticalLayout_25.addWidget(self.back_btn_5)
        self.rotateleft_btn = QtWidgets.QPushButton(self.rotate_menu)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/newPrefix/icons/rotateLeft.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon9.addPixmap(QtGui.QPixmap(":/newPrefix/icons/rotateLeft.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.rotateleft_btn.setIcon(icon9)
        self.rotateleft_btn.setCheckable(True)
        self.rotateleft_btn.setAutoExclusive(True)
        self.rotateleft_btn.setObjectName("rotateleft_btn")
        self.verticalLayout_25.addWidget(self.rotateleft_btn)
        self.rotaterigth_btn = QtWidgets.QPushButton(self.rotate_menu)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/newPrefix/icons/rotateRight.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon10.addPixmap(QtGui.QPixmap(":/newPrefix/icons/rotateRight.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.rotaterigth_btn.setIcon(icon10)
        self.rotaterigth_btn.setCheckable(True)
        self.rotaterigth_btn.setAutoExclusive(True)
        self.rotaterigth_btn.setObjectName("rotaterigth_btn")
        self.verticalLayout_25.addWidget(self.rotaterigth_btn)
        spacerItem3 = QtWidgets.QSpacerItem(20, 408, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_25.addItem(spacerItem3)
        self.stackedWidget_2.addWidget(self.page_8)
        self.show_image = QtWidgets.QLabel(self.page_2)
        self.show_image.setGeometry(QtCore.QRect(176, 30, 371, 361))
        self.show_image.setFrameShape(QtWidgets.QFrame.Box)
        self.show_image.setText("")
        self.show_image.setObjectName("show_image")
        self.undo_btn = QtWidgets.QPushButton(self.page_2)
        self.undo_btn.setGeometry(QtCore.QRect(200, 420, 91, 31))
        self.undo_btn.setStyleSheet("QPushButton {\n"
"background-color: #0e86f6;\n"
"        border-radius: 20px; \n"
"    color: white; /* Text color */\n"
"    font-weight: bold;\n"
"border:none; /* Border color */\n"
"    padding: 10px 10px; /* Adjust padding as needed */\n"
"    margin:0px; /* Margin to create distance between buttons */\n"
"}\n"
" QPushButton {\n"
"        border-radius: 10px; /* Adjust the value to change the curve radius */\n"
"    color: white; /* Text color */\n"
"    font-weight: bold;\n"
"\n"
"    padding: 10px 20px;\n"
"        /*height:50px;*/\n"
"margin: 0px;\n"
"        \n"
"        /* border-bottom: 1px solid #b0b0b0; */\n"
"    }\n"
" QPushButton:hover {\n"
"        background-color:#073c6d\n"
"    }")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/newPrefix/icons/undo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.undo_btn.setIcon(icon11)
        self.undo_btn.setObjectName("undo_btn")
        self.discard_btn = QtWidgets.QPushButton(self.page_2)
        self.discard_btn.setGeometry(QtCore.QRect(320, 420, 81, 31))
        self.discard_btn.setStyleSheet("QPushButton {\n"
"background-color: #0e86f6;\n"
"        border-radius: 20px; \n"
"    color: white; /* Text color */\n"
"    font-weight: bold;\n"
"border:none; /* Border color */\n"
"    padding: 10px 10px; /* Adjust padding as needed */\n"
"    margin:0px; /* Margin to create distance between buttons */\n"
"}\n"
" QPushButton {\n"
"        border-radius: 10px; /* Adjust the value to change the curve radius */\n"
"    color: white; /* Text color */\n"
"    font-weight: bold;\n"
"\n"
"    padding: 10px 20px;\n"
"        /*height:50px;*/\n"
"margin: 0px;\n"
"        \n"
"        /* border-bottom: 1px solid #b0b0b0; */\n"
"    }\n"
" QPushButton:hover {\n"
"        background-color:#073c6d\n"
"    }")
        self.discard_btn.setObjectName("discard_btn")
        self.save_btn = QtWidgets.QPushButton(self.page_2)
        self.save_btn.setGeometry(QtCore.QRect(440, 420, 91, 31))
        self.save_btn.setStyleSheet("QPushButton {\n"
"background-color: #0e86f6;\n"
"        border-radius: 20px; \n"
"    color: white; /* Text color */\n"
"    font-weight: bold;\n"
"border:none; /* Border color */\n"
"    padding: 10px 10px; /* Adjust padding as needed */\n"
"    margin:0px; /* Margin to create distance between buttons */\n"
"}\n"
" QPushButton {\n"
"        border-radius: 10px; /* Adjust the value to change the curve radius */\n"
"    color: white; /* Text color */\n"
"    font-weight: bold;\n"
"\n"
"    padding: 10px 20px;\n"
"        /*height:50px;*/\n"
"margin: 0px;\n"
"        \n"
"        /* border-bottom: 1px solid #b0b0b0; */\n"
"    }\n"
"\n"
" QPushButton:hover {\n"
"        background-color:#073c6d\n"
"    }")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/newPrefix/icons/save.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_btn.setIcon(icon12)
        self.save_btn.setObjectName("save_btn")
        self.stackedWidget.addWidget(self.page_2)
        self.show_page = QtWidgets.QLabel(self.centralwidget)
        self.show_page.setGeometry(QtCore.QRect(570, 10, 221, 551))
        self.show_page.setFrameShape(QtWidgets.QFrame.Box)
        self.show_page.setFrameShadow(QtWidgets.QFrame.Plain)
        self.show_page.setMidLineWidth(2)
        self.show_page.setText("")
        self.show_page.setObjectName("show_page")
        self.edit_btn = QtWidgets.QPushButton(self.centralwidget)
        self.edit_btn.setGeometry(QtCore.QRect(570, 570, 101, 31))
        self.edit_btn.setStyleSheet("QPushButton {\n"
"background-color: #0e86f6;\n"
"        border-radius: 20px; \n"
"    color: white; /* Text color */\n"
"    font-weight: bold;\n"
"border:none; /* Border color */\n"
"    padding: 10px 10px; /* Adjust padding as needed */\n"
"    margin:0px; /* Margin to create distance between buttons */\n"
"}\n"
" QPushButton {\n"
"        border-radius: 10px; /* Adjust the value to change the curve radius */\n"
"    color: white; /* Text color */\n"
"    font-weight: bold;\n"
"\n"
"    padding: 10px 20px;\n"
"        /*height:50px;*/\n"
"margin: 0px;\n"
"        \n"
"        /* border-bottom: 1px solid #b0b0b0; */\n"
"    }\n"
" QPushButton:hover {\n"
"        background-color:#073c6d\n"
"    }")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/newPrefix/edit.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.edit_btn.setIcon(icon13)
        self.edit_btn.setObjectName("edit_btn")
        self.ver_line = QtWidgets.QFrame(self.centralwidget)
        self.ver_line.setGeometry(QtCore.QRect(670, 560, 20, 61))
        self.ver_line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ver_line.setFrameShape(QtWidgets.QFrame.VLine)
        self.ver_line.setObjectName("ver_line")
        self.delete_btn = QtWidgets.QPushButton(self.centralwidget)
        self.delete_btn.setGeometry(QtCore.QRect(690, 570, 101, 31))
        self.delete_btn.setStyleSheet("QPushButton {\n"
"background-color: #0e86f6;\n"
"        border-radius: 20px; \n"
"    color: white; /* Text color */\n"
"    font-weight: bold;\n"
"border:none; /* Border color */\n"
"    padding: 10px 10px; /* Adjust padding as needed */\n"
"    margin:0px; /* Margin to create distance between buttons */\n"
"}\n"
" QPushButton {\n"
"        border-radius: 10px; /* Adjust the value to change the curve radius */\n"
"    color: white; /* Text color */\n"
"    font-weight: bold;\n"
"\n"
"    padding: 10px 20px;\n"
"        /*height:50px;*/\n"
"margin: 0px;\n"
"        \n"
"        /* border-bottom: 1px solid #b0b0b0; */\n"
"    }\n"
" QPushButton:hover {\n"
"        background-color:#073c6d\n"
"    }")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/newPrefix/icons/Delete.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_btn.setIcon(icon14)
        self.delete_btn.setObjectName("delete_btn")
        self.hor_line = QtWidgets.QFrame(self.centralwidget)
        self.hor_line.setGeometry(QtCore.QRect(600, 50, 171, 16))
        self.hor_line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.hor_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.hor_line.setObjectName("hor_line")
        self.pdf_btn = QtWidgets.QPushButton(self.centralwidget)
        self.pdf_btn.setGeometry(QtCore.QRect(590, 20, 191, 31))
        self.pdf_btn.setStyleSheet("QPushButton {\n"
"background-color: #0e86f6;\n"
"        border-radius: 20px; \n"
"    color: white; /* Text color */\n"
"    font-weight: bold;\n"
"border:none; /* Border color */\n"
"    padding: 10px 10px; /* Adjust padding as needed */\n"
"    margin:0px; /* Margin to create distance between buttons */\n"
"}\n"
" QPushButton {\n"
"        border-radius: 10px; /* Adjust the value to change the curve radius */\n"
"    color: white; /* Text color */\n"
"    font-weight: bold;\n"
"\n"
"    padding: 10px 20px;\n"
"        /*height:50px;*/\n"
"margin: 0px;\n"
"        \n"
"        /* border-bottom: 1px solid #b0b0b0; */\n"
"    }\n"
"QPushButton:hover {\n"
"        background-color:#073c6d\n"
"    }")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/newPrefix/icons/pdf_icon-icons.com_70898.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pdf_btn.setIcon(icon15)
        self.pdf_btn.setIconSize(QtCore.QSize(25, 25))
        self.pdf_btn.setCheckable(True)
        self.pdf_btn.setAutoExclusive(True)
        self.pdf_btn.setFlat(False)
        self.pdf_btn.setObjectName("pdf_btn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.stackedWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.adjust_btn.setText(_translate("MainWindow", "Adjust"))
        self.color_btn.setText(_translate("MainWindow", "Color Mode"))
        self.rotate_btn.setText(_translate("MainWindow", "Rotate"))
        self.crop_btn.setText(_translate("MainWindow", "Crop"))
        self.label_12.setText(_translate("MainWindow", "Adjust"))
        self.contrast_btn_3.setText(_translate("MainWindow", "Contrast"))
        self.sharp_btn_3.setText(_translate("MainWindow", "Sharpness"))
        self.label_13.setText(_translate("MainWindow", "Color Mode"))
        self.enhance_btn.setText(_translate("MainWindow", "Auto Enhance"))
        self.colorfil_btn.setText(_translate("MainWindow", "Color"))
        self.bnw_btn.setText(_translate("MainWindow", "Black and White"))
        self.gray_btn.setText(_translate("MainWindow", "Gray Scale"))
        self.nofil_btn.setText(_translate("MainWindow", "No filter"))
        self.label_14.setText(_translate("MainWindow", "Rotate"))
        self.rotateleft_btn.setText(_translate("MainWindow", "Rotate 90 left "))
        self.rotaterigth_btn.setText(_translate("MainWindow", "Rotate 90 right"))
        self.undo_btn.setText(_translate("MainWindow", "Undo"))
        self.discard_btn.setText(_translate("MainWindow", "Discard"))
        self.save_btn.setText(_translate("MainWindow", "Save"))
        self.edit_btn.setText(_translate("MainWindow", "edit"))
        self.delete_btn.setText(_translate("MainWindow", "delete"))
        self.pdf_btn.setText(_translate("MainWindow", "PDF"))
import Stackresource_rc
