# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/pdas/AppData/Local/Temp/StackDesignRrfcRO.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import Stackresource_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(775, 705) #605
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        MainWindow.setStyleSheet("background-color:white;")
        self.centralwidget.setObjectName("centralwidget")
        # self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        # self.stackedWidget.setGeometry(QtCore.QRect(10, 10, 151, 551))

        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")

        # Create stacked widget
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)

        # Creating a QVBoxLayout for the central widget
        # self.centralLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        # self.centralLayout.setObjectName("centralLayout")
         # Add widgets to the centralLayout
        

        self.stackedWidget.setObjectName("stackedWidget")
        
        

        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.stackedWidget.addWidget(self.page_5)
        self.menu = QtWidgets.QWidget(self.page_5)
        # self.menu.setGeometry(QtCore.QRect(0, 0, 151, 561))

        # Set layout for page_5
        self.page_5_layout = QtWidgets.QVBoxLayout(self.page_5)
        self.page_5_layout.setContentsMargins(0, 0, 0, 0)
        self.page_5_layout.setSpacing(0)
        self.menu.setFixedWidth(200)
        self.page_5_layout.addWidget(self.menu)
        self.menu.setStyleSheet("#menu {\n"
"        background-color:#ADD8E6 ;\n"#ADD8E6
"        width:50px;\n"
"    }\n"
"\n"
"    /* style for QPushButton and QLabel */\n"
"    #menu QPushButton, QLabel {\n"
"        height:40px;\n"
"        border:none;\n"
"        background-color:#ADD8E6 ;\n"
"        /* border-bottom: 1px solid #b0b0b0; */\n"
"    }\n"
"\n"
"    #menu QPushButton:hover {\n"
"        background-color: rgba( 86, 101, 115, 0.5);\n"
"    }\n"
"")
        self.menu.setObjectName("menu")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.menu)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_9 = QtWidgets.QLabel(self.menu)
        font = QtGui.QFont()
        font.setPointSize(22) #10
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_15.addWidget(self.label_9)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.adjust_btn = QtWidgets.QPushButton(self.menu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icons/adjust.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icons/adjust.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.adjust_btn.setIcon(icon)
        self.adjust_btn.setCheckable(True)
        self.adjust_btn.setAutoExclusive(True)
        self.adjust_btn.setFlat(False)
        self.adjust_btn.setObjectName("adjust_btn")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.adjust_btn.setFont(font)
        self.verticalLayout_16.addWidget(self.adjust_btn)
        self.color_btn = QtWidgets.QPushButton(self.menu)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/icons/ColorMode.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/icons/ColorMode.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.color_btn.setIcon(icon1)
        self.color_btn.setCheckable(True)
        self.color_btn.setAutoExclusive(True)
        self.color_btn.setObjectName("color_btn")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.color_btn.setFont(font)
        self.verticalLayout_16.addWidget(self.color_btn)
        self.rotate_btn = QtWidgets.QPushButton(self.menu)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/icons/rotate_113592.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rotate_btn.setIcon(icon2)
        self.rotate_btn.setObjectName("rotate_btn")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rotate_btn.setFont(font)
        self.verticalLayout_16.addWidget(self.rotate_btn)
        self.crop_btn = QtWidgets.QPushButton(self.menu)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/icons/crop.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/icons/crop.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.crop_btn.setIcon(icon3)
        self.crop_btn.setCheckable(True)
        self.crop_btn.setAutoExclusive(True)
        self.crop_btn.setObjectName("crop_btn")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.crop_btn.setFont(font)
        self.verticalLayout_16.addWidget(self.crop_btn)
        self.rename_btn = QtWidgets.QPushButton(self.menu)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/icons/Rename.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/icons/Rename.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.rename_btn.setIcon(icon4)
        self.rename_btn.setCheckable(True)
        self.rename_btn.setAutoExclusive(True)
        self.rename_btn.setObjectName("rename_btn")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rename_btn.setFont(font)
        self.verticalLayout_16.addWidget(self.rename_btn)
        self.pdf_btn = QtWidgets.QPushButton(self.menu)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/icons/pdf_icon-icons.com_70898.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/icons/pdf_icon-icons.com_70898.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pdf_btn.setIcon(icon5)
        self.pdf_btn.setCheckable(True)
        self.pdf_btn.setAutoExclusive(True)
        self.pdf_btn.setObjectName("pdf_btn")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pdf_btn.setFont(font)
        self.verticalLayout_16.addWidget(self.pdf_btn)
        self.delete_btn = QtWidgets.QPushButton(self.menu)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/icons/Delete.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/icons/Delete.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.delete_btn.setIcon(icon6)
        self.delete_btn.setCheckable(True)
        self.delete_btn.setAutoExclusive(True)
        self.delete_btn.setObjectName("delete_btn")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.delete_btn.setFont(font)
        self.verticalLayout_16.addWidget(self.delete_btn)
        self.verticalLayout_15.addLayout(self.verticalLayout_16)
        spacerItem = QtWidgets.QSpacerItem(20, 322, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem)
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")

        self.stackedWidget.addWidget(self.page_6)
        self.adjust_menu = QtWidgets.QWidget(self.page_6)
        # self.menu.setGeometry(QtCore.QRect(0, 0, 151, 561))

        # Set layout for page_6
        self.page_6_layout = QtWidgets.QVBoxLayout(self.page_6)
        self.page_6_layout.setContentsMargins(0, 0, 0, 0)
        self.page_6_layout.setSpacing(0)
        self.adjust_menu.setFixedWidth(200)
        self.page_6_layout.addWidget(self.adjust_menu)


        # self.adjust_menu = QtWidgets.QWidget(self.page_6)
        
        self.adjust_menu.setStyleSheet("#adjust_menu {\n"
"        background-color: #ADD8E6;\n"
"        width:50px;\n"
"    }\n"
"\n"
"    /* style for QPushButton and QLabel */\n"
"    #adjust_menu QPushButton, QLabel {\n"
"        height:40px;\n"
"        border:none;\n"
"        background-color:#ADD8E6 ;\n"
"        /* border-bottom: 1px solid #b0b0b0; */\n"
"    }\n"
"\n"
"    #adjust_menu QPushButton:hover {\n"
"        background-color: rgba( 86, 101, 115, 0.5);\n"
"    }\n"
"")
        self.adjust_menu.setObjectName("adjust_menu")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.adjust_menu)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_10 = QtWidgets.QLabel(self.adjust_menu)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_17.addWidget(self.label_10)
        self.back_btn = QtWidgets.QPushButton(self.adjust_menu)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.back_btn.setFont(font)
        self.back_btn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/newPrefix/icons/Back.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap(":/newPrefix/icons/Back.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.back_btn.setIcon(icon7)
        self.back_btn.setCheckable(True)
        self.back_btn.setAutoExclusive(True)
        self.back_btn.setObjectName("back_btn")
        self.verticalLayout_17.addWidget(self.back_btn)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.contrast_btn = QtWidgets.QPushButton(self.adjust_menu)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/newPrefix/icons/Contrast.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap(":/newPrefix/icons/Contrast.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.contrast_btn.setIcon(icon8)
        self.contrast_btn.setCheckable(True)
        self.contrast_btn.setAutoExclusive(True)
        self.contrast_btn.setObjectName("contrast_btn")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.contrast_btn.setFont(font)
        self.verticalLayout_18.addWidget(self.contrast_btn)
        self.sharp_btn = QtWidgets.QPushButton(self.adjust_menu)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/newPrefix/icons/sharpness.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon9.addPixmap(QtGui.QPixmap(":/newPrefix/icons/sharpness.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.sharp_btn.setIcon(icon9)
        self.sharp_btn.setObjectName("sharp_btn")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sharp_btn.setFont(font)
        self.verticalLayout_18.addWidget(self.sharp_btn)
        self.verticalLayout_17.addLayout(self.verticalLayout_18)
        spacerItem1 = QtWidgets.QSpacerItem(20, 406, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem1)
        self.stackedWidget.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")

        self.stackedWidget.addWidget(self.page_7)
        self.color_menu = QtWidgets.QWidget(self.page_7)
        # self.menu.setGeometry(QtCore.QRect(0, 0, 151, 561))

        # Set layout for page_6
        self.page_7_layout = QtWidgets.QVBoxLayout(self.page_7)
        self.page_7_layout.setContentsMargins(0, 0, 0, 0)
        self.page_7_layout.setSpacing(0)
        self.color_menu.setFixedWidth(200)
        self.page_7_layout.addWidget(self.color_menu)




        
        self.color_menu.setStyleSheet("#color_menu {\n"
"        background-color: #ADD8E6;\n"
"        width:50px;\n"
"    }\n"
"\n"
"    /* style for QPushButton and QLabel */\n"
"    #color_menu QPushButton, QLabel {\n"
"        height:40px;\n"
"        border:none;\n"
"        background-color:#ADD8E6 ;\n"
"        /* border-bottom: 1px solid #b0b0b0; */\n"
"    }\n"
"\n"
"    #color_menu QPushButton:hover {\n"
"        background-color: rgba( 86, 101, 115, 0.5);\n"
"    }\n"
"")
        self.color_menu.setObjectName("color_menu")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.color_menu)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_11 = QtWidgets.QLabel(self.color_menu)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_19.addWidget(self.label_11)
        self.back_btn_2 = QtWidgets.QPushButton(self.color_menu)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.back_btn_2.setFont(font)
        self.back_btn_2.setText("")
        self.back_btn_2.setIcon(icon7)
        self.back_btn_2.setCheckable(True)
        self.back_btn_2.setAutoExclusive(True)
        self.back_btn_2.setObjectName("back_btn_2")
        self.verticalLayout_19.addWidget(self.back_btn_2)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.enhance_btn = QtWidgets.QPushButton(self.color_menu)
        self.enhance_btn.setObjectName("enhance_btn")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.enhance_btn.setFont(font)
        self.verticalLayout_20.addWidget(self.enhance_btn)
        self.colorfil_btn = QtWidgets.QPushButton(self.color_menu)
        self.colorfil_btn.setObjectName("colorfil_btn")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.colorfil_btn.setFont(font)
        self.verticalLayout_20.addWidget(self.colorfil_btn)
        self.bnw_btn = QtWidgets.QPushButton(self.color_menu)
        self.bnw_btn.setObjectName("bnw_btn")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bnw_btn.setFont(font)
        self.verticalLayout_20.addWidget(self.bnw_btn)
        self.gray_btn = QtWidgets.QPushButton(self.color_menu)
        self.gray_btn.setObjectName("gray_btn")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gray_btn.setFont(font)
        self.verticalLayout_20.addWidget(self.gray_btn)
        self.nofil_btn = QtWidgets.QPushButton(self.color_menu)
        self.nofil_btn.setObjectName("nofil_btn")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nofil_btn.setFont(font)
        self.verticalLayout_20.addWidget(self.nofil_btn)
        self.verticalLayout_19.addLayout(self.verticalLayout_20)
        spacerItem2 = QtWidgets.QSpacerItem(20, 321, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem2)
        self.stackedWidget.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")

        self.stackedWidget.addWidget(self.page_8)
        self.rotate_menu = QtWidgets.QWidget(self.page_8)
        # self.menu.setGeometry(QtCore.QRect(0, 0, 151, 561))

        # Set layout for page_8
        self.page_8_layout = QtWidgets.QVBoxLayout(self.page_8)
        self.page_8_layout.setContentsMargins(0, 0, 0, 0)
        self.page_8_layout.setSpacing(0)
        self.rotate_menu.setFixedWidth(200)
        self.page_8_layout.addWidget(self.rotate_menu)



        self.rotate_menu.setStyleSheet("#rotate_menu {\n"
"        background-color: #ADD8E6;\n"
"        width:50px;\n"
"    }\n"
"\n"
"    /* style for QPushButton and QLabel */\n"
"    #rotate_menu QPushButton, QLabel {\n"
"        height:40px;\n"
"        border:none;\n"
"        background-color:#ADD8E6 ;\n"
"        /* border-bottom: 1px solid #b0b0b0; */\n"
"    }\n"
"\n"
"    #rotate_menu QPushButton:hover {\n"
"        background-color: rgba( 86, 101, 115, 0.5);\n"
"    }\n"
"")
        self.rotate_menu.setObjectName("rotate_menu")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.rotate_menu)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_12 = QtWidgets.QLabel(self.rotate_menu)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_21.addWidget(self.label_12)
        self.back_btn_3 = QtWidgets.QPushButton(self.rotate_menu)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.back_btn_3.setFont(font)
        self.back_btn_3.setText("")
        self.back_btn_3.setIcon(icon7)
        self.back_btn_3.setCheckable(True)
        self.back_btn_3.setAutoExclusive(True)
        self.back_btn_3.setObjectName("back_btn_3")
        self.verticalLayout_21.addWidget(self.back_btn_3)
        self.rotateleft_btn = QtWidgets.QPushButton(self.rotate_menu)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/newPrefix/icons/rotateLeft.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon10.addPixmap(QtGui.QPixmap(":/newPrefix/icons/rotateLeft.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.rotateleft_btn.setIcon(icon10)
        self.rotateleft_btn.setCheckable(True)
        self.rotateleft_btn.setAutoExclusive(True)
        self.rotateleft_btn.setObjectName("rotateleft_btn")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rotateleft_btn.setFont(font)
        self.verticalLayout_21.addWidget(self.rotateleft_btn)
        self.rotaterigth_btn = QtWidgets.QPushButton(self.rotate_menu)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/newPrefix/icons/rotateRight.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon11.addPixmap(QtGui.QPixmap(":/newPrefix/icons/rotateRight.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.rotaterigth_btn.setIcon(icon11)
        self.rotaterigth_btn.setCheckable(True)
        self.rotaterigth_btn.setAutoExclusive(True)
        self.rotaterigth_btn.setObjectName("rotaterigth_btn")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rotaterigth_btn.setFont(font)
        self.verticalLayout_21.addWidget(self.rotaterigth_btn)
        spacerItem3 = QtWidgets.QSpacerItem(20, 408, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_21.addItem(spacerItem3)
        self.stackedWidget.addWidget(self.page_8)



#         self.show_page = QtWidgets.QWidget(self.centralwidget)
#         self.show_page.setGeometry(QtCore.QRect(570, 19, 201, 541))
#         self.show_page.setObjectName("show_page")
#         # Create show page layout
#         self.show_page_layout = QtWidgets.QVBoxLayout()
#         self.show_page_layout.setContentsMargins(0, 0, 0, 0)
#         self.show_page_layout.setSpacing(0)
#         self.show_page = QtWidgets.QWidget()
#         self.show_page.setLayout(self.show_page_layout)
#         # Set fixed width for show_page
#         self.show_page.setFixedWidth(100)


# #         self.camera_frame = QtWidgets.QFrame(self.show_page)
# #         self.camera_frame.setGeometry(QtCore.QRect(10, 10, 141, 81))
        
# #         self.camera_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
# #         self.camera_frame.setFrameShadow(QtWidgets.QFrame.Raised)
# #         self.camera_frame.setObjectName("camera_frame")
# #         self.pushButton = QtWidgets.QPushButton(self.camera_frame)
# #         self.pushButton.setGeometry(QtCore.QRect(0, 0, 141, 81))
# #         self.pushButton.setText("")
# #         icon12 = QtGui.QIcon()
# #         icon12.addPixmap(QtGui.QPixmap(":/newPrefix/icons/camera48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
# #         icon12.addPixmap(QtGui.QPixmap(":/newPrefix/icons/camera48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
# #         self.pushButton.setIcon(icon12)
# #         self.pushButton.setIconSize(QtCore.QSize(40, 40))
# #         self.pushButton.setCheckable(True)
# #         self.pushButton.setAutoExclusive(True)
# #         self.pushButton.setFlat(True)
# #         self.pushButton.setObjectName("pushButton")
# #         self.camHor_line = QtWidgets.QFrame(self.show_page)
# #         self.camHor_line.setGeometry(QtCore.QRect(0, 90, 181, 20))
# #         self.camHor_line.setStyleSheet("#camHor_line{\n"
# # "color: rgb(0, 0, 0),\n"
# # "}")
# #         self.camHor_line.setFrameShape(QtWidgets.QFrame.HLine)
# #         self.camHor_line.setFrameShadow(QtWidgets.QFrame.Sunken)
# #         self.camHor_line.setObjectName("camHor_line")
# #         self.line = QtWidgets.QFrame(self.show_page)
# #         self.line.setGeometry(QtCore.QRect(-21, -10, 61, 561))
# #         self.line.setFrameShape(QtWidgets.QFrame.VLine)
# #         self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
# #         self.line.setObjectName("line")
# #         MainWindow.setCentralWidget(self.centralwidget)

# #         # Set central widget and layout
# #         MainWindow.setCentralWidget(self.centralwidget)

# #         self.retranslateUi(MainWindow)
# #         self.stackedWidget.setCurrentIndex(2)
# #         QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        

#         # Add camera_frame to show page
#         self.camera_frame = QtWidgets.QFrame()
#         self.camera_frame.setObjectName("camera_frame")
#         self.camera_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
#         self.camera_frame.setFrameShadow(QtWidgets.QFrame.Raised)
#         self.show_page_layout.addWidget(self.camera_frame)

        

#         # Add pushButton to camera_frame
#         self.pushButton = QtWidgets.QPushButton(self.camera_frame)
#         self.pushButton.setObjectName("pushButton")
#         self.pushButton.setText("")
#         icon12 = QtGui.QIcon()
#         icon12.addPixmap(QtGui.QPixmap(":/newPrefix/icons/camera48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
#         icon12.addPixmap(QtGui.QPixmap(":/newPrefix/icons/camera48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
#         self.pushButton.setIcon(icon12)
#         self.pushButton.setIconSize(QtCore.QSize(40, 40))
#         self.pushButton.setCheckable(True)
#         self.pushButton.setAutoExclusive(True)
#         self.pushButton.setFlat(True)
#         self.pushButton.setObjectName("pushButton")

#         # Add camHor_line to camera_frame
#         self.camHor_line = QtWidgets.QFrame()
#         self.camHor_line.setObjectName("camHor_line")
#         self.camHor_line.setStyleSheet("#camHor_line{\n"
#                                     "color: black;\n"
#                                     "border: 2px solid black;\n"
#                                     "}")
#         self.camHor_line.setFrameShape(QtWidgets.QFrame.HLine)
#         self.camHor_line.setFrameShadow(QtWidgets.QFrame.Sunken)
#         # Add spacer item to move camHor_line downwards
#         # spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
#         # self.show_page_layout.addItem(spacerItem)
#         self.show_page_layout.addWidget(self.camHor_line,0)

#         # Add line to show page
#         self.line = QtWidgets.QFrame()
#         self.line.setObjectName("line")
#         self.line.setMinimumWidth(100)  # Set minimum width for line
#         self.line.setFrameShape(QtWidgets.QFrame.VLine)
#         self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
#         # Add spacer item to move line to the right
#         spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
#         self.show_page_layout.addItem(spacerItem2)

#         self.show_page_layout.addWidget(self.line)

#         self.gridLayout.addWidget(self.show_page, 0, 1, 1, 1)
        
        # self.show_page_label = QtWidgets.QLabel(self.centralwidget)
        # self.show_page_label.setObjectName("show_page_label")
        # self.show_page_label.setStyleSheet("background-color: cyan;")  # Set background color to white

        # # Set fixed width for the label
        # self.show_page_label.setFixedWidth(200)

        # # Create a QVBoxLayout for the show_page_label
        # self.show_page_layout = QtWidgets.QVBoxLayout(self.show_page_label)
        # self.show_page_layout.setContentsMargins(0, 0, 0, 0)
        # self.show_page_layout.setSpacing(0)
        # # Add camera_frame to show page
        # self.camera_frame = QtWidgets.QFrame()
        # self.camera_frame.setObjectName("camera_frame")
        # self.camera_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        # self.camera_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        # self.show_page_layout.addWidget(self.camera_frame)

        # # Add layout to camera_frame
        # camera_frame_layout = QtWidgets.QVBoxLayout(self.camera_frame)

        # # Add pushButton to camera_frame_layout
        # self.pushButton = QtWidgets.QPushButton()
        # self.pushButton.setObjectName("pushButton")
        # self.pushButton.setText("")
        # icon12 = QtGui.QIcon()
        # icon12.addPixmap(QtGui.QPixmap(":/newPrefix/icons/camera48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # icon12.addPixmap(QtGui.QPixmap(":/newPrefix/icons/camera48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        # self.pushButton.setIcon(icon12)
        # self.pushButton.setIconSize(QtCore.QSize(40, 40))
        # self.pushButton.setCheckable(True)
        # self.pushButton.setAutoExclusive(True)
        # self.pushButton.setFlat(True)
        # self.pushButton.setObjectName("pushButton")
        # camera_frame_layout.addWidget(self.pushButton)

        # # Set alignment for the layout
        # camera_frame_layout.setAlignment(QtCore.Qt.AlignRight)

        # # Add push button to the layout
        # self.show_page_layout.addWidget(self.pushButton, alignment=QtCore.Qt.AlignRight)
        # # Add the show_page_label to the grid layout with right alignment
        # self.gridLayout.addWidget(self.show_page_label, 0, 1, 1, 1, alignment=QtCore.Qt.AlignRight)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(620, 10, 141, 571))
        self.label.setText("")
        self.label.setObjectName("label")
        self.show_page = QtWidgets.QLabel(self.centralwidget)
        self.show_page.setGeometry(QtCore.QRect(590, 10, 171, 551))
        self.show_page.setFrameShape(QtWidgets.QFrame.Box)
        self.show_page.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.show_page.setMidLineWidth(2)
        self.show_page.setText("")
        self.show_page.setObjectName("show_page")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(620, 90, 121, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.scan_btn = QtWidgets.QPushButton(self.centralwidget)
        self.scan_btn.setGeometry(QtCore.QRect(20, 20, 75, 61))
        self.scan_btn.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/newPrefix/icons/camera48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.scan_btn.setIcon(icon12)
        self.scan_btn.setIconSize(QtCore.QSize(50, 50))
        self.scan_btn.setCheckable(True)
        self.scan_btn.setAutoExclusive(True)
        self.scan_btn.setFlat(True)
        self.scan_btn.setObjectName("scan_btn")
        self.show_image = QtWidgets.QLabel(self.centralwidget)
        self.show_image.setGeometry(QtCore.QRect(250, 20, 391, 541))
        self.show_image.setText("")
        self.show_image.setObjectName("show_image")

        # Add the show_page label to the grid layout with right alignment
        self.gridLayout.addWidget(self.show_page, 0, 1, 1, 1, alignment=QtCore.Qt.AlignRight)
        # Create a layout for show_page
        self.show_page_layout = QtWidgets.QVBoxLayout(self.show_page)
        self.show_page_layout.setContentsMargins(0, 0, 0, 0)
        self.show_page_layout.setSpacing(0)

        self.show_page_layout.addWidget(self.scan_btn)
        self.show_page_layout.addWidget(self.line)

        # self.setLayout(self.gridLayout)
        self.show_page.setFixedWidth(200)
        # Add spacer item to adjust position of scan_btn
        spacer_item = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.show_page_layout.addItem(spacer_item)
       
        # self.gridLayout.addWidget(self.show_image, 0, 1, 1, 1, alignment=QtCore.Qt.AlignCenter)

        # Create the display_image box
        self.display_image_box = QtWidgets.QVBoxLayout()
        self.display_image_box.setSpacing(0)
        self.display_image_box.setContentsMargins(0, 0, 0, 0)

        # Create a frame for the display_image box
        self.display_image_frame = QtWidgets.QFrame(self.centralwidget)
        self.display_image_frame.setFrameShape(QtWidgets.QFrame.Box)
        # self.display_image_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.display_image_frame.setMidLineWidth(2)
        self.display_image_frame.setObjectName("display_image_frame")

        # Set layout for the frame
        self.display_image_frame.setLayout(self.display_image_box)

        # Add the display_image frame to the show_page_layout
        self.show_page_layout.addWidget(self.display_image_frame)
        self.display_image_frame.setFixedHeight(600)
        


        
        # Set central widget and layout
        MainWindow.setCentralWidget(self.centralwidget)
        
        self.retranslateUi(MainWindow)
        
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_9.setText(_translate("MainWindow", "DashBoard"))
        self.adjust_btn.setText(_translate("MainWindow", "Adjust"))
        self.color_btn.setText(_translate("MainWindow", "Color Mode"))
        self.rotate_btn.setText(_translate("MainWindow", "Rotate"))
        self.crop_btn.setText(_translate("MainWindow", "Crop"))
        self.rename_btn.setText(_translate("MainWindow", "Rename"))
        self.pdf_btn.setText(_translate("MainWindow", "PDF"))
        self.delete_btn.setText(_translate("MainWindow", "Delete"))
        self.label_10.setText(_translate("MainWindow", "Adjust"))
        self.contrast_btn.setText(_translate("MainWindow", "Contrast"))
        self.sharp_btn.setText(_translate("MainWindow", "Sharpness"))
        self.label_11.setText(_translate("MainWindow", "Color Mode"))
        self.enhance_btn.setText(_translate("MainWindow", "Auto Enhance"))
        self.colorfil_btn.setText(_translate("MainWindow", "Color"))
        self.bnw_btn.setText(_translate("MainWindow", "Black and White"))
        self.gray_btn.setText(_translate("MainWindow", "Gray Scale"))
        self.nofil_btn.setText(_translate("MainWindow", "No filter"))
        self.label_12.setText(_translate("MainWindow", "Rotate"))
        self.rotateleft_btn.setText(_translate("MainWindow", "Rotate 90 left "))
        self.rotaterigth_btn.setText(_translate("MainWindow", "Rotate 90 right"))

    
